### ISSUE TITLE
Add/remove firewall rules during service start/stop

### ISSUE THREAD

**Issue by lynxthecat** [lynxthecat/cake-qos-simple#13]
It's clearly desirable to move away from the use of the separate cake-qos-simple.nft file and amalgamate the add/remove of firewall rules with the service script. 

In preparation for this, I have moved out the configuration parameters to a config file to be stored in /root/cake-qos-simple/config.sh.

It seems to me desirable to set the firewall rules in dependence upon some extra configuration parameters included in this config file using the nftables - see here: https://wiki.nftables.org/wiki-nftables/index.php/Quick_reference-nftables_in_10_minutes#Rules. 

@dave14305, @mattytap any thoughts?

**Comment by dave14305** [comment]
https://wiki.nftables.org/wiki-nftables/index.php/Atomic_rule_replacement

https://wiki.nftables.org/wiki-nftables/index.php/Scripting

Using individual nft commands doesn’t leverage the atomic rule replacement features.

You can deal with the variables by passing them on the command-line:
```
nft --define IFACE_NAMES=br-lan -f /usr/share/nftables.d/ruleset-post/cake-qos-simple.nft 
```

**Comment by lynxthecat** [comment]
Understood. So how about we just create file as heredoc and load that in?

**Comment by dave14305** [comment]
> Understood. So how about we just create file as heredoc and load that in?

Load what exactly? All of the nftables rules? If so, why? What about the user that wants to expand the vmap dports or add sets?

**Comment by lynxthecat** [comment]
Can't those get set in dependence on variables set in config file? So the nft file is just generated on the fly as heredoc by the service script in dependence on what is set in config.

**Comment by dave14305** [comment]
I haven’t seen any configuration file in the repo yet. What are you planning to have in that file?

**Comment by lynxthecat** [comment]
OK I've added a new branch: 'restructure'  with this commit: https://github.com/lynxthecat/cake-qos-simple/commit/e40b834478f381e814b32cc0c055eb2f102b46df. 

Now /root/cake-qos-simple/config.sh stores the configuration parameters. This should make updating the service script more straightforward. In the future, some validation of configuration parameters could be added such as checking that the config.sh file specifies a certain set of parameters. 

Does this make sense to you?

In terms of the firewall rules, I am still not sure what the best way to proceed is - I'd also value your thoughts on this. 

Some ideas I have:

- store cake-qos-simple.nft inside /root/cake-qos-simple/ and load and unload that;

- optionally, cake-qos-simple could itself generate cake-qos-simple.nft based on configuration parameters set in config.sh. 

What do you think?

**Comment by mattytap** [comment]
Regarding nftable rules, I'd generate the nft on the fly and store somewhere in /tmp before loading. Similar to the config based nft rules in dscpconfig.

**Comment by dave14305** [comment]
You can run it like this (just an example from my last iteration of the rules):
```
nft -f - <<EOF
add table inet cake-qos-simple
delete table inet cake-qos-simple
add table inet cake-qos-simple
add chain inet cake-qos-simple classify-postrouting { type filter hook postrouting priority mangle + 1; policy accept; }
add chain inet cake-qos-simple classify-and-store-dscp
add chain inet cake-qos-simple classify-dscp
add chain inet cake-qos-simple dscp_set_bulk
add chain inet cake-qos-simple dscp_set_besteffort
add chain inet cake-qos-simple dscp_set_video
add chain inet cake-qos-simple dscp_set_voice
add chain inet cake-qos-simple store-dscp-in-conntrack
add map inet cake-qos-simple rules_proto_dport { type inet_proto . inet_service : verdict; }
add element inet cake-qos-simple rules_proto_dport { tcp . 53 : goto dscp_set_voice }
add element inet cake-qos-simple rules_proto_dport { udp . 53 : goto dscp_set_voice }
add element inet cake-qos-simple rules_proto_dport { tcp . 853 : goto dscp_set_voice }
add element inet cake-qos-simple rules_proto_dport { udp . 853 : goto dscp_set_voice }
add element inet cake-qos-simple rules_proto_dport { udp . 123 : goto dscp_set_voice }
add rule inet cake-qos-simple classify-postrouting oifname "wan" ct mark & 0x00000080 == 0x00000000 goto classify-and-store-dscp
add rule inet cake-qos-simple classify-and-store-dscp jump classify-dscp
add rule inet cake-qos-simple classify-and-store-dscp jump store-dscp-in-conntrack
add rule inet cake-qos-simple classify-dscp meta l4proto . th dport vmap @rules_proto_dport
add rule inet cake-qos-simple dscp_set_bulk ip dscp set cs1 counter
add rule inet cake-qos-simple dscp_set_bulk ip6 dscp set cs1 counter
add rule inet cake-qos-simple dscp_set_besteffort ip dscp set cs0 counter
add rule inet cake-qos-simple dscp_set_besteffort ip6 dscp set cs0 counter
add rule inet cake-qos-simple dscp_set_video ip dscp set cs2 counter
add rule inet cake-qos-simple dscp_set_video ip6 dscp set cs2 counter
add rule inet cake-qos-simple dscp_set_voice ip dscp set cs4 counter
add rule inet cake-qos-simple dscp_set_voice ip6 dscp set cs4 counter
add rule inet cake-qos-simple store-dscp-in-conntrack ct mark set ip dscp
add rule inet cake-qos-simple store-dscp-in-conntrack ct mark set ip6 dscp
add rule inet cake-qos-simple store-dscp-in-conntrack ct mark set ct mark | 0x00000080 counter
EOF
```
I think this is uglier to follow and understand, and you can’t do anything conditional within the heredoc, AFAIK.

**Comment by lynxthecat** [comment]
@dave14305 I think you can alter heredoc with variables - see this example from cake-autorate:

```
	cat > "${run_path}/log_file_export" <<- EOT
	#!/bin/bash

	timeout_s=\${1:-20}

	if kill -USR1 "${proc_pids['maintain_log_file']}"
	then
		printf "Successfully signalled maintain_log_file process to request log file export.\n"
	else
		printf "ERROR: Failed to signal maintain_log_file process.\n" >&2
		exit 1
	fi
	rm -f "${run_path}/last_log_file_export"

	read_try=0

	while [[ ! -f "${run_path}/last_log_file_export" ]]
	do
		sleep 1
		if (( ++read_try >= \${timeout_s} ))
		then
			printf "ERROR: Timeout (\${timeout_s}s) reached before new log file export identified.\n" >&2
			exit 1
		fi
	done

	read -r log_file_export_path < "${run_path}/last_log_file_export"

	printf "Log file export complete.\n"

	printf "Log file available at location: "
	printf "\${log_file_export_path}\n"
	EOT
```

https://github.com/lynxthecat/cake-autorate/blob/d1159520db1aa3782bb862d354179172bee0f57b/cake-autorate.sh#L204

**Comment by dave14305** [comment]
Yes you can, but I think of variables as substitution versus a conditional if/else or for/while loop in case you need to iterate over any config rules.

**Comment by dave14305** [comment]
And to put all this in perspective, OpenWrt had to invent the `ucode` language to deal with these issues creating firewall4 rules for nftables…

**Comment by lynxthecat** [comment]
So @dave14305 do you think the best option for now would be simply to move cake-qos-simple.nft to /root/cake-qos-simple/ and then use the nft add and remove calls from that file?

**Comment by dave14305** [comment]
That’s for you to decide. My idea was put forth in PR #10 and it morphed into this quagmire.

**Comment by lynxthecat** [comment]
How about this: https://github.com/lynxthecat/cake-qos-simple/commit/34b153b144fbbd165cbd627771d6037dbe00f6a4. 

- cake-qos-simple will check for existence of config or nftables.rules inside /root/cake-qos-simple/
- if either do not exist it will error out and offer options to generate a corresponding default file
- default config file can be generated with `service cake-qos-simple generate_config`
- default nftables.rules file can be generated with `service cake-qos-simple generate_nft_rules`
- if user tries to generate either when a corresponding file already exists .new is appended to the generated file

Thus now we can just update the service file with new config or nftables defaults, and user can retain own config / nftables.rules file, and decide which changes to merge in as necessary by comparing the .new with the previously stored config or nftables.rules file. 

I may be missing one or two things here, but so far so good from my own testing.

One issue I have not figured out is how to properly maintain indentation in the generated nftables file. See this line:

https://github.com/lynxthecat/cake-qos-simple/blob/34b153b144fbbd165cbd627771d6037dbe00f6a4/cake-qos-simple#L75

It's not a huge deal though as it's still pretty readable without the indentation. 

Thoughts @dave14305 and @mattytap?

**Comment by dave14305** [comment]
> One issue I have not figured out is how to properly maintain indentation in the generated nftables file. See this line:

Remove the dash in the heredoc. It indicates tab suppression.

**Comment by lynxthecat** [comment]
What's the best way to handle this?

```
generate_config()
{
        printf "Generating new default config for cake-qos-simple.\n"

        mkdir -p "${PREFIX}"

        cat > "${PREFIX}/config.tmp" <<EOT
        # cake-qos-simple configuration options

        ul_if=wan # upload interface
        dl_if=""  # download interface override (normally left blank and IFB derived for $ul_if ingress)

        cake_ul_rate_Mbps=20  # cake upload rate in Mbit/s
        cake_dl_rate_Mbps=20 # cake download rate in Mbit/s

        cake_ul_options="diffserv4 triple-isolate nat wash ack-filter noatm overhead 0"
        cake_dl_options="diffserv4 triple-isolate nat nowash ingress no-ack-filter noatm overhead 0"

        overwrite_ecn_val_ul=0 # overwrite existing ecn bits with decimal value (e.g. 0, 1, 2, 3), else "" to disable
        overwrite_ecn_val_dl=0 # overwrite existing ecn bits with decimal value (e.g. 0, 1, 2, 3), else "" to disable
EOT
```

Looks ugly because the indentation in the code is wrong, and outputs everything with indent. 

How can I retain proper indentation in the script function context, but ignore that first tab associated with that proper indentation when outputting the file? @rany2 perhaps you have an idea for this?

See e.g. here: 

https://github.com/lynxthecat/cake-qos-simple/blob/34b153b144fbbd165cbd627771d6037dbe00f6a4/cake-qos-simple#L107

**Comment by lynxthecat** [comment]
And now with this commit: https://github.com/lynxthecat/cake-qos-simple/commit/13500bda053a1ce854400089dd56f7251f8284b5 I have incorporated nftables variables into the config. 

```
root@OpenWrt-1:~/cake-qos-simple# cat config
# cake-qos-simple configuration options

ul_if=wan # upload interface
dl_if=""  # download interface override (normally left blank and IFB derived for  ingress)

cake_ul_rate_Mbps=20  # cake upload rate in Mbit/s
cake_dl_rate_Mbps=20 # cake download rate in Mbit/s

cake_ul_options="diffserv4 triple-isolate nat wash ack-filter noatm overhead 0"
cake_dl_options="diffserv4 triple-isolate nat nowash ingress no-ack-filter noatm overhead 0"

overwrite_ecn_val_ul=0 # overwrite existing ecn bits with decimal value (e.g. 0, 1, 2, 3), else "" to disable
overwrite_ecn_val_dl=0 # overwrite existing ecn bits with decimal value (e.g. 0, 1, 2, 3), else "" to disable

# the following nftables variables will be used to generate a default nft.rules file

nft_rules_vars="# ### START OF CUSTOMISABLE NFT VARS SECTION (DO NOT DELETE THIS LINE) ###

# correspondence between protocol, destination port and DSCPs
define PROTO_DPORT_DSCP_MAP = {
tcp . 53 : goto dscp_set_voice,  # DNS
udp . 53 : goto dscp_set_voice,  # DNS
tcp . 853 : goto dscp_set_voice, # DNS-over-TLS
udp . 853 : goto dscp_set_voice, # DNS-over-TLS
udp . 123 : goto dscp_set_voice  # NTP
}

# local MAC addresses to set to bulk (e.g. IoT devices)
define BULK_MACS = {
00:00:00:00:00:00
}
# ### END OF CUSTOMISABLE NFT VARS SECTION (DO NOT DELETE THIS LINE) ###"
```
These get imported into the automatically generated nft.rules file. 

```
root@OpenWrt-1:~/cake-qos-simple# cat nft.rules
# cake-qos-simple nftables rules

# This nft script:
# 1) classifies DSCPs (to supplement or replace those set by LAN clients); and
# 2) stores DSCPs in conntracks for restoration using tc action ctinfo dscp 63 128

table inet cake-qos-simple
delete table inet cake-qos-simple

# ### START OF CUSTOMISABLE NFT VARS SECTION (DO NOT DELETE THIS LINE) ###

# correspondence between protocol, destination port and DSCPs
define PROTO_DPORT_DSCP_MAP = {
tcp . 53 : goto dscp_set_voice,  # DNS
udp . 53 : goto dscp_set_voice,  # DNS
tcp . 853 : goto dscp_set_voice, # DNS-over-TLS
udp . 853 : goto dscp_set_voice, # DNS-over-TLS
udp . 123 : goto dscp_set_voice  # NTP
}

# local MAC addresses to set to bulk (e.g. IoT devices)
define BULK_MACS = {
00:00:00:00:00:00
}
# ### END OF CUSTOMISABLE NFT VARS SECTION (DO NOT DELETE THIS LINE) ###
```
